[package]
name = "game-media-vault-infrastructure"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
blake3.workspace = true
game-media-vault-application.workspace = true
game-media-vault-domain.workspace = true
rusqlite.workspace = true
serde_json.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Storage_FileSystem"] }

[dev-dependencies]
tempfile.workspace = true
